language: ruby
dist: trusty
sudo: required
cache: bundler
addons:
  postgresql: 9.5
services:
  - postgresql
script: "bundle exec rake spec"
rvm:
  - 2.5.0
notifications:
    on_success: change
    on_failure: always
    on_start: false
