dist: trusty
sudo: required
language: ruby
cache: bundler
addons:
  postgresql: 9.5
services:
  - postgresql
script:
  - bundle exec rake spec
rvm:
  - 2.6.2
notifications:
    on_success: false
    on_failure: false
    on_start: false
